# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: Testing CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - name: install packages
        run: |
          R -e "install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org'))"
          R -e "remotes::install_github('rstudio/renv@0.15.4')"
          R -e 'renv::restore()'
      - name: testing
        run: testthat::test_dir("tests")
        shell: Rscript {0}